#!/usr/bin/bash
#//Hanya tools gabungan yang cupu//
#//Script Kiddies//
kiddies='\e[1;31m'
kiddes='\e[1;33m'
echo ""
printf "   $WHI ============================================================ \n"
printf "            $RED######                           #####  \n"      
printf "            $RED######                           #####      \n"   
printf "            $RED##########                  ##########        \n" 
printf "                $RED######                  ######            \n" 
printf "                $RED######                  ######            \n" 
printf "                $RED######                  ######            \n" 
printf "            $RED######################################        \n" 
printf "            $RED######################################        \n" 
printf "            $RED######################################        \n" 
printf "        $RED##############################################    \n" 
printf "        $RED##########   ####################    #########    \n" 
printf "        $RED##########   ####################    #########    \n" 
printf "    $RED######################################################\n" 
printf "    $RED######################################################\n" 
printf "    $RED######################################################\n" 
printf "    $RED######################################################\n" 
printf "    $RED#####   ######################################   #####\n" 
printf "    $RED#####   ######################################   #####\n" 
printf "    $RED#####   ######################################   #####\n" 
printf "    $RED#####   ######                           #####   #####\n" 
printf "    $RED#####   ######                           #####   #####\n" 
printf "    $RED#####   ######                           #####   #####\n" 
printf "    $RED#####   ##################   #################   #####\n" 
printf "                $RED##############   #############            \n" 
printf "                $RED##############   #############            \n" 
printf "                $RED##############   #############\n" 
printf "   $WHI ============================================================ \n"
printf "   $YELLOW		     TOOLS AND CHECKER AMPAS				\n"
printf "   $WHI ============================================================ \n"			
printf "   $YELLOW		        [THANKS TO]		\n"
printf "   $YELLOW	[✓] BC0DE.NET | STUCK-CREW.NET | UANG.HARAM \n"
printf "   $YELLOW     [✓] SGB TEAM REBORN | AlchaDecode | CCOCOT.CO \n"
printf "   $WHI ============================================================  \n"
printf "$NC\n"
echo -e $kiddies"============================================================" 
echo " [1] AGOODA ACCOUNT CHECKER"  | lolcat
echo " [2] JOOX ACCOUNT CHECKER" | lolcat
echo " [3] MY INDIHOME ACCOUNT CHECKER" | lolcat
echo " [4] STARBUX ACCOUNT CHECKER" | lolcat
echo " [5] BOOKMYSHOW ACCOUNT CHECKER" | lolcat
echo " [6] BASH EMAIL FILTER" | lolcat
echo " [7] MD5 MASS DECODERS" | lolcat
echo " [0] MEMILIH UNTUK KELUAR SAJA" | lolcat
echo -e $kiddies"============================================================"
read -p " [Pilih No]> " File;

if [ $File = 1 ] || [ $File = 01 ]
then
echo "============================================================"
bash agodaaccountchecker.sh;
fi

if [ $File = 2 ] || [ $File = 02 ]
then
echo "============================================================"
bash jooxaccountchecker.sh;
fi

if [ $File = 3 ] || [ $File = 03 ]
then
echo "============================================================"
bash myindihomeaccountchecker.sh;
fi

if [ $File = 4 ] || [ $File = 04 ]
then
echo "============================================================"
bash starbuxaccountchecker.sh;
fi

if [ $File = 5 ] || [ $File = 05 ]
then
echo "============================================================"
bash bmsaccountchecker.sh mailistbms.txt;
fi

if [ $File = 6 ] || [ $File = 06 ]
then
echo "============================================================"
bash bashemailfilter.sh;
fi

if [ $File = 7 ] || [ $File = 07 ]
then
echo "============================================================"
bash md5massdecoders.sh;
fi

if [ $File = 0 ] || [ $File = 00 ]
then
echo "============================================================"
echo "THANKS FOR STUCK CREW TOOLS"
sleep 3
fi